package conntrack

// code generated by enum2go.

type CntlMsgTypes int
const (
	IpctnlMsgCtNew CntlMsgTypes = 0
	IpctnlMsgCtGet CntlMsgTypes = 1
	IpctnlMsgCtDelete CntlMsgTypes = 2
	IpctnlMsgCtGetCtrzero CntlMsgTypes = 3
	IpctnlMsgCtGetStatsCpu CntlMsgTypes = 4
	IpctnlMsgCtGetStats CntlMsgTypes = 5
	IpctnlMsgCtGetDying CntlMsgTypes = 6
	IpctnlMsgCtGetUnconfirmed CntlMsgTypes = 7
	IpctnlMsgMax CntlMsgTypes = 8
)

type CtattrCounters int
const (
	CtaCountersUnspec CtattrCounters = 0
	CtaCountersPackets CtattrCounters = 1
	CtaCountersBytes CtattrCounters = 2
	CtaCounters32Packets CtattrCounters = 3
	CtaCounters32Bytes CtattrCounters = 4
	CtaCountersMax CtattrCounters = 5
)

